version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*" # Group all Actions updates into a single larger pull request
    schedule:
      interval: weekly
